//
// Swagger Petstore
// 
// This is a sample Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
// 
// API version: 1.0.0
// Contact: apiteam@swagger.io
//
// Code generated by OpenAPI Generator (https://http://github.com/openAPITools/openapi-generator)

package handler

import (
  "time"
)

// APIResponse model
type APIResponse struct {
  // Code field
  Code int32 `json:"code,omitempty" validate:"-"`
  // Type field
  Type string `json:"type,omitempty" validate:"-"`
  // Message field
  Message string `json:"message,omitempty" validate:"-"`
}

// Category model
type Category struct {
  // ID field
  ID int64 `json:"id,omitempty" validate:"-"`
  // Name field
  Name string `json:"name,omitempty" validate:"-"`
}

// InlineObject model: test
type InlineObject struct {
  // ID field
  ID int64 `json:"id,omitempty" validate:"-"`
}

// InlineObject1 model
type InlineObject1 struct {
  // Name field: Updated name of the pet
  Name string `json:"name,omitempty" validate:"-"`
  // Status field: Updated status of the pet
  Status string `json:"status,omitempty" validate:"-"`
}

// Order model
type Order struct {
  // ID field
  ID int64 `json:"id,omitempty" validate:"-"`
  // PetID field
  PetID int64 `json:"petId,omitempty" validate:"-"`
  // Quantity field
  Quantity int32 `json:"quantity,omitempty" validate:"-"`
  // ShipDate field
  ShipDate time.Time `json:"shipDate,omitempty" validate:"-"`
  // Status field: Order Status
  Status string `json:"status,omitempty" validate:"-"`
  // Complete field
  Complete bool `json:"complete,omitempty" default:"true" validate:"-"`
}

// Pet model: test
type Pet struct {
  // ID field
  ID int64 `json:"id,omitempty" validate:"gte=10,lte=100"`
  // Category field
  Category Category `json:"category,omitempty" validate:"-"`
  // Name field
  Name string `json:"name" validate:"required"`
  // PhotoUrls field
  PhotoUrls array `json:"photoUrls" validate:"required"`
  // Tags field
  Tags array `json:"tags,omitempty" validate:"-"`
  // Status field: pet status in the store
  Status string `json:"status,omitempty" validate:"-"`
}

// Tag model
type Tag struct {
  // ID field
  ID int64 `json:"id,omitempty" validate:"-"`
  // Name field
  Name string `json:"name,omitempty" validate:"-"`
}

// User model
type User struct {
  // ID field
  ID int64 `json:"id,omitempty" validate:"-"`
  // Username field
  Username string `json:"username,omitempty" validate:"-"`
  // FirstName field
  FirstName string `json:"firstName,omitempty" validate:"lte=10"`
  // LastName field
  LastName string `json:"lastName,omitempty" validate:"-"`
  // Email field
  Email string `json:"email,omitempty" validate:"-"`
  // Password field
  Password string `json:"password,omitempty" validate:"-"`
  // Phone field
  Phone string `json:"phone,omitempty" validate:"-"`
  // UserStatus field: User Status
  UserStatus int32 `json:"userStatus,omitempty" validate:"-"`
}
