//
// Swagger Petstore
// 
// This is a sample Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
// 
// API version: 1.0.0
// Contact: apiteam@swagger.io
//
// Code generated by OpenAPI Generator (https://http://github.com/openAPITools/openapi-generator)

// Package test contains all API models and handlers
package test

import (
  "net/http"
)

// TestMethodOutput is the output for the TestMethod operation
type TestMethodOutput struct {
  // Body payload
  Body array `json:"-"`
}

// Render manages response payloads.
func (p *TestMethodOutput) Render(w http.ResponseWriter, r *http.Request) (err error) {
  w.WriteHeader(200)
  return
}

// MarshalJSON marshals the body as JSON
func (p *TestMethodOutput) MarshalJSON() ([]byte, error) {
  return json.Marshal(&p.Body);
}
