//
// Swagger Petstore
// 
// This is a sample Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
// 
// API version: 1.0.0
// Contact: apiteam@swagger.io
//
// Code generated by OpenAPI Generator (https://http://github.com/openAPITools/openapi-generator)

// Package handler contains all API models and handlers
package handler

import (
	"net/http"

	"github.com/go-chi/chi"
	"github.com/phogolabs/rest"
)

// TestAPI handler
type TestAPI struct{
 // TODO: add your dependencies here
}

// Mount mounts the TestAPI handler
func (h *TestAPI) Mount(r chi.Router) {
  r.Group(func(r chi.Router) {
     r.Get("/test", h.testMethod)
  })
}

// TestMethod operation
// @return array
func (h *TestAPI) testMethod(w http.ResponseWriter, r *http.Request) {
  //TODO: implement the operation testMethod

  output := &TestMethodOutput{}
  rest.Render(w, r, output)
}

